[build]
  command = "prisma generate && next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  PRISMA_CLI_BINARY_TARGETS = "native,rhel-openssl-1.0.x,rhel-openssl-3.0.x,debian-openssl-3.0.x"

[functions]
  included_files = ["node_modules/.prisma/client/**", "prisma/schema.prisma"]
